language: php

matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm


env:
  - SYMFONY_VERSION="3.0.*" DB=mysql
