# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGE_CHAMPIONS, ROLE_ALLOWED_TO_SWITCH]
        # ROLE_ALLOWED_TO_SWITCH, gives aportunity to switch user
        # insert in the URL ?_switch_user=test1@gmail.com
        # to exit user insert ?_switch_user=exit
        # this should be automated in admin

    access_control:
                            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
                            - { path: ^/verify, roles: IS_AUTHENTICATED_ANONYMOUSLY }
                            - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
                            - { path: ^/forgot_password, roles:  IS_AUTHENTICATED_ANONYMOUSLY }
                            - { path: ^/admin, roles: ROLE_ADMIN }
                            - { path: ^/, roles:  IS_AUTHENTICATED_FULLY }
    encoders:
        AppBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: AppBundle:User, property: email }
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800
                path:     /

            switch_user: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
